/**:
  ros__parameters:
    time_pass_thresh: 300.0 #60.0
    align_dt: 0.5
    clipper:
      sigma: 0.8 # 0.4
      epsilon: 6 # 0.6
      mindist: 0.0 #0.1
      volume_epsilon: 0.0
      min_associations: 4